-- ============================================================================
-- Migration 002 — CURE restructure (May 2026)
--
-- See spec/MEMBERSHIP.md §3.2 for the canonical description.
-- Apply in the Supabase SQL editor after 001_membership.sql.
--
-- Adds:
--   - cure_applications table (the CURE Club application queue)
--   - members.tier text       (CHECK enum: arty / cure / cure_founder)
--   - members.founder_number  (unique, FND-XXXX, generated by trigger)
--   - members.cure_application_id  (FK back to cure_applications, nullable)
--   - generate_founder_number()    trigger function for FND-XXXX
--   - back-fill statements         that derive tier from existing booleans
-- ============================================================================

-- ----------------------------------------------------------------------------
-- cure_applications — public-facing application queue for CURE Club.
-- Created BEFORE the FK on members.cure_application_id can reference it.
-- ----------------------------------------------------------------------------
create table cure_applications (
  id                      uuid primary key default gen_random_uuid(),
  email                   text not null,
  name                    text not null,

  -- For upgrades from Arty: the existing member's email. Null for fresh apps.
  existing_member_email   text references members(email) on delete set null,

  -- The 5 questions (or 3, for upgrades) as a JSON object keyed by question id.
  -- See src/content/apply-questions.json for canonical shape.
  questionnaire           jsonb not null,

  status                  text not null default 'pending'
                            check (status in ('pending', 'accepted', 'rejected', 'withdrawn')),

  decided_at              timestamptz,
  decided_by              text,                    -- admin identifier (e.g. 'matthew')
  decision_notes          text,                    -- internal-only context for the decision

  -- After accept: the Stripe Checkout session URL sent to the applicant.
  -- Null on pending / rejected / withdrawn. Useful for resend-on-request.
  checkout_session_url    text,

  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

create index cure_applications_status_created_idx
  on cure_applications (status, created_at desc);
create index cure_applications_email_lower_idx
  on cure_applications (lower(email));

-- Auto-touch updated_at (re-uses the function from 001).
create trigger cure_applications_updated_at
  before update on cure_applications
  for each row
  execute function members_touch_updated_at();

-- ----------------------------------------------------------------------------
-- members — new columns
-- ----------------------------------------------------------------------------

-- Supplementary tier classifier. Set by the application + admin flow.
-- Distinct from arty_active / cure_active which remain the live "is this
-- person currently in good standing" signal driven by the Stripe webhook.
--   arty           — paid Arty subscriber (default tier on plain Arty signup)
--   cure           — paid CURE subscriber (admin-accepted application →
--                    Stripe Checkout success → tier flipped to 'cure')
--   cure_founder   — founder member, granted by Matthew. No Stripe sub.
alter table members
  add column tier text
    check (tier in ('arty', 'cure', 'cure_founder'));

-- Founder member number — separate sequence from MEM-XXXX.
-- Format: FND-XXXX, zero-padded to 4 digits. Null for non-founders.
alter table members
  add column founder_number text unique;

-- Link back to the cure_applications row, if the member came via an
-- application. Null for plain Arty signups and direct founder grants.
alter table members
  add column cure_application_id uuid
    references cure_applications(id) on delete set null;

create index members_tier_idx              on members (tier);
create index members_founder_number_idx    on members (founder_number);

-- Founder number generation: FND-0001, FND-0002, ...
create or replace function generate_founder_number()
returns trigger as $$
declare
  next_num int;
begin
  select coalesce(
    max(cast(substring(founder_number from 'FND-(\d+)') as int)),
    0
  ) + 1
    into next_num
    from members;
  new.founder_number := 'FND-' || lpad(next_num::text, 4, '0');
  return new;
end;
$$ language plpgsql;

-- Fires only when tier='cure_founder' and founder_number is null. Covers
-- both direct founder-creation INSERTs and admin-promotion UPDATEs.
create trigger members_set_founder_number
  before insert or update on members
  for each row
  when (new.tier = 'cure_founder' and new.founder_number is null)
  execute function generate_founder_number();

-- ----------------------------------------------------------------------------
-- Back-fill tier for rows that existed before this migration ran.
-- v1 "Both Clubs" rows (arty_active=true AND cure_active=true) collapse to
-- 'cure' — in v2 CURE includes Arty by definition.
-- ----------------------------------------------------------------------------
update members set tier = 'cure' where cure_active = true and tier is null;
update members set tier = 'arty' where arty_active = true and cure_active = false and tier is null;
